/* The following code was generated by JFlex 1.6.1 */

package ucu;

import java_cup.runtime.Symbol;
import java.util.*;
import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/home/fernando/UCU/Compiladores/while/src/main/ucu/Lexer.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner, sym {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\46\1\2\1\50\1\46\1\46\22\0\1\46\1\10\1\1"+
    "\3\0\1\11\1\0\1\12\1\13\1\14\1\15\1\0\1\16\1\0"+
    "\1\4\12\44\1\0\1\17\1\20\1\21\3\0\6\6\24\45\1\0"+
    "\1\3\2\0\1\45\1\0\1\30\1\7\1\6\1\22\1\24\1\27"+
    "\1\41\1\35\1\31\1\45\1\32\1\25\1\45\1\36\1\23\1\33"+
    "\1\45\1\37\1\26\1\34\1\5\1\47\1\40\3\45\1\42\1\0"+
    "\1\43\7\0\1\50\u1fa2\0\1\50\1\50\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\1\1\3\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\1\1\13\11\3"+
    "\1\14\1\15\1\16\1\3\1\0\1\17\3\0\1\20"+
    "\1\21\1\22\1\23\5\3\1\24\4\3\1\0\1\2"+
    "\2\0\11\3\2\0\1\2\1\3\1\25\1\3\1\26"+
    "\2\3\1\27\1\30\1\3\1\0\2\3\1\31\1\32"+
    "\1\33\1\0\1\3\1\34\1\35";

  private static int [] zzUnpackAction() {
    int [] result = new int[83];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\173\0\244\0\315\0\51\0\366"+
    "\0\51\0\51\0\51\0\51\0\51\0\51\0\u011f\0\u0148"+
    "\0\u0171\0\u019a\0\u01c3\0\u01ec\0\u0215\0\u023e\0\u0267\0\u0290"+
    "\0\u02b9\0\51\0\51\0\u02e2\0\u030b\0\122\0\51\0\u0334"+
    "\0\u035d\0\u0386\0\51\0\51\0\51\0\315\0\u03af\0\u03d8"+
    "\0\u0401\0\u042a\0\u0453\0\315\0\u047c\0\u04a5\0\u04ce\0\u04f7"+
    "\0\u0520\0\51\0\u0549\0\u0572\0\u059b\0\u05c4\0\u05ed\0\u0616"+
    "\0\u063f\0\u0668\0\u0691\0\u06ba\0\u06e3\0\u070c\0\u0735\0\u0549"+
    "\0\u075e\0\315\0\u0787\0\315\0\u07b0\0\u07d9\0\315\0\315"+
    "\0\u0802\0\u082b\0\u0854\0\u087d\0\315\0\315\0\315\0\u08a6"+
    "\0\u08cf\0\315\0\315";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[83];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\3\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\6\1\22\1\23\1\24\1\25\1\6\1\26"+
    "\1\6\1\27\1\30\3\6\1\31\1\6\1\32\1\33"+
    "\1\34\1\6\1\4\1\35\52\0\1\36\1\37\1\0"+
    "\1\40\45\36\2\0\1\4\43\0\2\4\5\0\1\41"+
    "\7\0\1\42\41\0\3\6\12\0\20\6\2\0\2\6"+
    "\1\0\1\6\12\0\1\43\60\0\1\44\50\0\1\45"+
    "\34\0\3\6\12\0\1\6\1\46\1\47\15\6\2\0"+
    "\2\6\1\0\1\6\6\0\3\6\12\0\3\6\1\50"+
    "\14\6\2\0\2\6\1\0\1\6\6\0\3\6\12\0"+
    "\2\6\1\51\15\6\2\0\2\6\1\0\1\6\6\0"+
    "\3\6\12\0\10\6\1\52\7\6\2\0\2\6\1\0"+
    "\1\6\6\0\3\6\12\0\6\6\1\53\11\6\2\0"+
    "\2\6\1\0\1\6\6\0\3\6\12\0\5\6\1\54"+
    "\12\6\2\0\2\6\1\0\1\6\6\0\3\6\12\0"+
    "\15\6\1\55\2\6\2\0\2\6\1\0\1\6\6\0"+
    "\3\6\12\0\13\6\1\56\1\6\1\57\2\6\2\0"+
    "\2\6\1\0\1\6\6\0\3\6\12\0\13\6\1\60"+
    "\4\6\2\0\2\6\1\0\1\6\45\0\1\34\6\0"+
    "\1\4\2\0\3\6\12\0\20\6\2\0\2\6\1\4"+
    "\1\35\2\0\1\36\1\0\2\36\1\61\1\0\1\36"+
    "\17\0\1\36\4\0\1\36\1\0\2\36\11\0\2\41"+
    "\1\62\46\41\14\63\1\64\34\63\5\0\3\6\12\0"+
    "\5\6\1\65\12\6\2\0\2\6\1\0\1\6\6\0"+
    "\3\6\12\0\4\6\1\66\13\6\2\0\2\6\1\0"+
    "\1\6\6\0\3\6\12\0\14\6\1\67\3\6\2\0"+
    "\2\6\1\0\1\6\6\0\3\6\12\0\7\6\1\70"+
    "\10\6\2\0\2\6\1\0\1\6\6\0\3\6\12\0"+
    "\3\6\1\71\14\6\2\0\2\6\1\0\1\6\6\0"+
    "\3\6\12\0\7\6\1\72\10\6\2\0\2\6\1\0"+
    "\1\6\6\0\3\6\12\0\2\6\1\73\15\6\2\0"+
    "\2\6\1\0\1\6\6\0\1\74\2\6\12\0\20\6"+
    "\2\0\2\6\1\0\1\6\6\0\3\6\12\0\7\6"+
    "\1\75\10\6\2\0\2\6\1\0\1\6\7\0\2\76"+
    "\12\0\1\76\1\0\1\76\2\0\2\76\13\0\1\76"+
    "\4\0\14\63\1\77\40\63\1\100\7\63\1\64\34\63"+
    "\5\0\3\6\12\0\7\6\1\101\10\6\2\0\2\6"+
    "\1\0\1\6\6\0\3\6\12\0\2\6\1\102\15\6"+
    "\2\0\2\6\1\0\1\6\6\0\3\6\12\0\17\6"+
    "\1\103\2\0\2\6\1\0\1\6\6\0\3\6\12\0"+
    "\11\6\1\104\6\6\2\0\2\6\1\0\1\6\6\0"+
    "\3\6\12\0\4\6\1\105\13\6\2\0\2\6\1\0"+
    "\1\6\6\0\3\6\12\0\14\6\1\106\3\6\2\0"+
    "\2\6\1\0\1\6\6\0\3\6\12\0\14\6\1\107"+
    "\3\6\2\0\2\6\1\0\1\6\6\0\3\6\12\0"+
    "\2\6\1\110\15\6\2\0\2\6\1\0\1\6\6\0"+
    "\3\6\12\0\3\6\1\111\14\6\2\0\2\6\1\0"+
    "\1\6\7\0\2\112\12\0\1\112\1\0\1\112\2\0"+
    "\2\112\13\0\1\112\4\0\4\63\1\62\7\63\1\64"+
    "\34\63\5\0\3\6\12\0\14\6\1\113\3\6\2\0"+
    "\2\6\1\0\1\6\6\0\3\6\12\0\12\6\1\114"+
    "\5\6\2\0\2\6\1\0\1\6\6\0\3\6\12\0"+
    "\2\6\1\115\15\6\2\0\2\6\1\0\1\6\6\0"+
    "\3\6\12\0\12\6\1\116\5\6\2\0\2\6\1\0"+
    "\1\6\6\0\3\6\12\0\2\6\1\117\15\6\2\0"+
    "\2\6\1\0\1\6\7\0\2\120\12\0\1\120\1\0"+
    "\1\120\2\0\2\120\13\0\1\120\11\0\3\6\12\0"+
    "\2\6\1\121\15\6\2\0\2\6\1\0\1\6\6\0"+
    "\3\6\12\0\13\6\1\122\4\6\2\0\2\6\1\0"+
    "\1\6\7\0\2\36\12\0\1\36\1\0\1\36\2\0"+
    "\2\36\13\0\1\36\11\0\3\6\12\0\1\123\17\6"+
    "\2\0\2\6\1\0\1\6\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2296];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\1\1\6\11\13\1\2\11"+
    "\2\1\1\0\1\11\3\0\3\11\13\1\1\0\1\11"+
    "\2\0\11\1\2\0\12\1\1\0\5\1\1\0\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[83];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

	public static List<Symbol> tokens(Reader input) throws IOException {
		Lexer lexer = new Lexer(input);
		List<Symbol> result = new ArrayList<Symbol>();
		for (Symbol token = lexer.next_token(); token.sym != sym.EOF; token = lexer.next_token()) {
			result.add(token);
		}
		return result;
	}

	public static void main(String[] args) throws IOException {
		Lexer lexer;
		if (args.length < 1) args = new String[]{ "" };
		for (int i = 0; i < args.length; ++i) {
			lexer = new Lexer(new InputStreamReader(args[i].length() > 0 ? new FileInputStream(args[i]) : System.in, "UTF8"));
			System.out.println(args[i] +":");
			for (Symbol token = lexer.next_token(); token.sym != sym.EOF; token = lexer.next_token()) {
				System.out.println("\t#"+ token.sym +" "+ token.value);
			}
		}
	}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 166) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return new Symbol(error, yyline, yycolumn, "Unexpected input <"+ yytext() +">!");
            }
          case 30: break;
          case 2: 
            { /* Ignore */
            }
          case 31: break;
          case 3: 
            { String $1 = yytext(); String $0;
	  $0 = $1;
	  return new Symbol(ID, yyline, yycolumn, $0);
            }
          case 32: break;
          case 4: 
            { return new Symbol(EXCLAMATION_MARK, yyline, yycolumn, yytext());
            }
          case 33: break;
          case 5: 
            { return new Symbol(LEFT_PARENTHESIS, yyline, yycolumn, yytext());
            }
          case 34: break;
          case 6: 
            { return new Symbol(RIGHT_PARENTHESIS, yyline, yycolumn, yytext());
            }
          case 35: break;
          case 7: 
            { return new Symbol(ASTERISK, yyline, yycolumn, yytext());
            }
          case 36: break;
          case 8: 
            { return new Symbol(PLUS_SIGN, yyline, yycolumn, yytext());
            }
          case 37: break;
          case 9: 
            { return new Symbol(HYPHEN_MINUS, yyline, yycolumn, yytext());
            }
          case 38: break;
          case 10: 
            { return new Symbol(SEMICOLON, yyline, yycolumn, yytext());
            }
          case 39: break;
          case 11: 
            { return new Symbol(EQUALS_SIGN, yyline, yycolumn, yytext());
            }
          case 40: break;
          case 12: 
            { return new Symbol(LEFT_CURLY_BRACKET, yyline, yycolumn, yytext());
            }
          case 41: break;
          case 13: 
            { return new Symbol(RIGHT_CURLY_BRACKET, yyline, yycolumn, yytext());
            }
          case 42: break;
          case 14: 
            { String $1 = yytext(); Double $0 = Double.parseDouble($1);
	  return new Symbol(NUM, yyline, yycolumn, $0);
            }
          case 43: break;
          case 15: 
            { return new Symbol(STR, yyline, yycolumn, yytext().substring(1,yytext().length()-1));
            }
          case 44: break;
          case 16: 
            { return new Symbol(DOUBLE_AMPERSAND, yyline, yycolumn, yytext());
            }
          case 45: break;
          case 17: 
            { return new Symbol(LESS_THAN_OR_EQUAL, yyline, yycolumn, yytext());
            }
          case 46: break;
          case 18: 
            { return new Symbol(DOUBLE_EQUALS_SIGN, yyline, yycolumn, yytext());
            }
          case 47: break;
          case 19: 
            { return new Symbol(DO, yyline, yycolumn, yytext());
            }
          case 48: break;
          case 20: 
            { return new Symbol(IF, yyline, yycolumn, yytext());
            }
          case 49: break;
          case 21: 
            { return new Symbol(ELSE, yyline, yycolumn, yytext());
            }
          case 50: break;
          case 22: 
            { return new Symbol(SKIP, yyline, yycolumn, yytext());
            }
          case 51: break;
          case 23: 
            { return new Symbol(THEN, yyline, yycolumn, yytext());
            }
          case 52: break;
          case 24: 
            { return new Symbol(TRUE, yyline, yycolumn, yytext());
            }
          case 53: break;
          case 25: 
            { return new Symbol(FALSE, yyline, yycolumn, yytext());
            }
          case 54: break;
          case 26: 
            { return new Symbol(PRINT, yyline, yycolumn, yytext());
            }
          case 55: break;
          case 27: 
            { return new Symbol(WHILE, yyline, yycolumn, yytext());
            }
          case 56: break;
          case 28: 
            { return new Symbol(LENGTH, yyline, yycolumn, yytext());
            }
          case 57: break;
          case 29: 
            { return new Symbol(DEFINED, yyline, yycolumn, yytext());
            }
          case 58: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
